project:
  type: website
  output-dir: docs
  preview:
    port: 7780
website:
  title: "notes-model-thinking"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml
  site-url: https://orenbochman.github.io/notes-model-thinking/
  description: Personal website, portfolio and blog
  repo-url: https://github.com/OrenBochman/notes-model-thinking
  repo-actions: [edit, issue]
  #favicon: favicon.ico
  page-footer:
    right: "This page is built with 💛 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023-2025, Oren Bochman"
    background: "#AB0520" # AZ Red

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    from: "markdown+emoji"
    reference-location: margin
    citation: true
    citation-location: document
    page-layout: full
    ipynb-shell-interactivity: all 
    anchor-sections: true
    code-fold: false
    html-math-method: katex
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
    smooth-scroll: true
    image: images/nlp-brain-wordcloud.jpg
    #title-block-banner: images/banner_black_3.jpg
    image-placeholder: images/dnn_cover.png
    title-block-banner: images/banner_deep.jpg

bibliography: references.bib

editor: 
  markdown: 
    wrap: sentence
    #wrap: 72    
from: markdown+emoji
